'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property saveregex() As String
            Get
                Return CType(Me("saveregex"),String)
            End Get
            Set
                Me("saveregex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property regexin1() As String
            Get
                Return CType(Me("regexin1"),String)
            End Get
            Set
                Me("regexin1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property regexin2() As String
            Get
                Return CType(Me("regexin2"),String)
            End Get
            Set
                Me("regexin2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property regexthis() As String
            Get
                Return CType(Me("regexthis"),String)
            End Get
            Set
                Me("regexthis") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property regexfor() As String
            Get
                Return CType(Me("regexfor"),String)
            End Get
            Set
                Me("regexfor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SauvegardeLR() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("SauvegardeLR"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("SauvegardeLR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComboBoxLangsourceDeeplV() As Boolean
            Get
                Return CType(Me("ComboBoxLangsourceDeeplV"),Boolean)
            End Get
            Set
                Me("ComboBoxLangsourceDeeplV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxLangsourceDeeplL() As String
            Get
                Return CType(Me("ComboBoxLangsourceDeeplL"),String)
            End Get
            Set
                Me("ComboBoxLangsourceDeeplL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxLangTargetDeeplL() As String
            Get
                Return CType(Me("ComboBoxLangTargetDeeplL"),String)
            End Get
            Set
                Me("ComboBoxLangTargetDeeplL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ComboBoxLangtargetDeeplV() As Boolean
            Get
                Return CType(Me("ComboBoxLangtargetDeeplV"),Boolean)
            End Get
            Set
                Me("ComboBoxLangtargetDeeplV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxLangsourceGogL() As String
            Get
                Return CType(Me("ComboBoxLangsourceGogL"),String)
            End Get
            Set
                Me("ComboBoxLangsourceGogL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ComboBoxLangsourceGogV() As Boolean
            Get
                Return CType(Me("ComboBoxLangsourceGogV"),Boolean)
            End Get
            Set
                Me("ComboBoxLangsourceGogV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxLangtargetGogL() As String
            Get
                Return CType(Me("ComboBoxLangtargetGogL"),String)
            End Get
            Set
                Me("ComboBoxLangtargetGogL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ComboBoxLangtargetGogV() As Boolean
            Get
                Return CType(Me("ComboBoxLangtargetGogV"),Boolean)
            End Get
            Set
                Me("ComboBoxLangtargetGogV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxLangsourceYandL() As String
            Get
                Return CType(Me("ComboBoxLangsourceYandL"),String)
            End Get
            Set
                Me("ComboBoxLangsourceYandL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ComboBoxLangsourceYandV() As Boolean
            Get
                Return CType(Me("ComboBoxLangsourceYandV"),Boolean)
            End Get
            Set
                Me("ComboBoxLangsourceYandV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxLangtargetYandL() As String
            Get
                Return CType(Me("ComboBoxLangtargetYandL"),String)
            End Get
            Set
                Me("ComboBoxLangtargetYandL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ComboBoxLangtargetYandV() As Boolean
            Get
                Return CType(Me("ComboBoxLangtargetYandV"),Boolean)
            End Get
            Set
                Me("ComboBoxLangtargetYandV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComboBoxtraducteur() As String
            Get
                Return CType(Me("ComboBoxtraducteur"),String)
            End Get
            Set
                Me("ComboBoxtraducteur") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Rackamtranslate.My.MySettings
            Get
                Return Global.Rackamtranslate.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
